### ISSUE TITLE
KeyError: 'megaphone'

### ISSUE THREAD

**Issue by tudoanh** [danleyb2/Instagram-API#14]
Hello, when I'm using InstagramAPI in my code, I have this Exception. Could you please fix it?

```python
Unhandled exception in thread started by <function wrapper at 0x7fd8e9cd9410>
Traceback (most recent call last):
  File "/home/tu/.virtualenvs/money_tool/local/lib/python2.7/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/home/tu/.virtualenvs/money_tool/local/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 113, in inner_run
    autoreload.raise_last_exception()
  File "/home/tu/.virtualenvs/money_tool/local/lib/python2.7/site-packages/django/utils/autoreload.py", line 249, in raise_last_exception
    six.reraise(*_exception)
  File "/home/tu/.virtualenvs/money_tool/local/lib/python2.7/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/home/tu/.virtualenvs/money_tool/local/lib/python2.7/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/tu/.virtualenvs/money_tool/local/lib/python2.7/site-packages/django/apps/registry.py", line 115, in populate
    app_config.ready()
  File "/home/tu/.virtualenvs/money_tool/local/lib/python2.7/site-packages/django/contrib/admin/apps.py", line 23, in ready
    self.module.autodiscover()
  File "/home/tu/.virtualenvs/money_tool/local/lib/python2.7/site-packages/django/contrib/admin/__init__.py", line 26, in autodiscover
    autodiscover_modules('admin', register_to=site)
  File "/home/tu/.virtualenvs/money_tool/local/lib/python2.7/site-packages/django/utils/module_loading.py", line 50, in autodiscover_modules
    import_module('%s.%s' % (app_config.name, module_to_search))
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/tu/Project/money_tool/admin_page/cute_things/admin.py", line 6, in <module>
    from .instagram import upload_photo
  File "/home/tu/Project/money_tool/admin_page/cute_things/instagram.py", line 13, in <module>
    insta.login()
  File "/home/tu/.virtualenvs/money_tool/local/lib/python2.7/site-packages/InstagramAPI/src/Instagram.py", line 220, in login
    check = self.timelineFeed()
  File "/home/tu/.virtualenvs/money_tool/local/lib/python2.7/site-packages/InstagramAPI/src/Instagram.py", line 247, in timelineFeed
    return TimelineFeedResponse(self.http.request('feed/timeline/')[1])
  File "/home/tu/.virtualenvs/money_tool/local/lib/python2.7/site-packages/InstagramAPI/src/http/Response/TimelineFeedResponse.py", line 35, in __init__
    self.megaphone = FeedAysf(response['megaphone']['feed_aysf'])
KeyError: 'megaphone'
```

Now I'm comment that line to work around with it. Just want to let's you know.

**Comment by danleyb2** [comment]
will be fixed when translation reaches mgp25/Instagram-API@6b8f07aec4cb42b58e61e5f456b373d2f6351850

Added as Todo danleyb2/Instagram-API@96820c1d3d7eccce4a80fc2447486d53ac37421c
