### ISSUE TITLE
No module named 'Checkpoint'

### ISSUE THREAD

**Issue by qsniyg** [danleyb2/Instagram-API#23]
$ python test.py
    Traceback (most recent call last):
      File "test.py", line 1, in <module>
        from InstagramAPI import Instagram
      File "/usr/lib/python3.6/site-packages/InstagramAPI/__init__.py", line 1, in <module>
        from .src import *
      File "/usr/lib/python3.6/site-packages/InstagramAPI/src/__init__.py", line 1, in <module>
        from Checkpoint import Checkpoint
    ModuleNotFoundError: No module named 'Checkpoint'

**Comment by danleyb2** [comment]
python2.7 works okay though
