### ISSUE TITLE
Exception while logging in

### ISSUE THREAD

**Issue by antonid08** [danleyb2/Instagram-API#37]
Hi! 
I got excepion while logging in (when 'tray' is None). I can reproduce it not at all accounts.
`Traceback (most recent call last):
  File "/home/antonid08/PycharmProjects/instagramcrm/InstagramWorker/logic/Comments.py", line 69, in <module>
    comments_worker.set_user('nom_app1', 'nom123nom123')
  File "/home/antonid08/PycharmProjects/instagramcrm/InstagramWorker/logic/Comments.py", line 26, in set_user
    self.__login_if_need(login, password)
  File "/home/antonid08/PycharmProjects/instagramcrm/InstagramWorker/logic/Comments.py", line 47, in __login_if_need
    self.api_client.login()  # TODO check can raise exception
  File "/home/antonid08/.virtualenvs/InstagramVirtualEnv/local/lib/python2.7/site-packages/InstagramAPI/src/Instagram.py", line 232, in login
    self.getReelsTrayFeed()
  File "/home/antonid08/.virtualenvs/InstagramVirtualEnv/local/lib/python2.7/site-packages/InstagramAPI/src/Instagram.py", line 1149, in getReelsTrayFeed
    feed = ReelsTrayFeedResponse(self.http.request('feed/reels_tray/')[1])
  File "/home/antonid08/.virtualenvs/InstagramVirtualEnv/local/lib/python2.7/site-packages/InstagramAPI/src/http/Response/ReelsTrayFeedResponse.py", line 16, in __init__
    if 'items' in tray and  len(tray['items']):
TypeError: object of type 'NoneType' has no len()`

**Comment by onemanarmy8** [comment]
https://github.com/danleyb2/Instagram-API/pull/32
