### ISSUE TITLE
Cant approve pending request

### ISSUE THREAD

**Issue by antonid08** [danleyb2/Instagram-API#38]
Hi.
When i try to approve pending request: 
`Traceback (most recent call last):
  File "/usr/lib/pycharm/helpers/pydev/pydevd.py", line 1596, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/usr/lib/pycharm/helpers/pydev/pydevd.py", line 974, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/antonid08/PycharmProjects/instagramcrm/InstagramWorker/tasks/tasks.py", line 139, in <module>
    update_instagram_data()
  File "/home/antonid08/PycharmProjects/instagramcrm/InstagramWorker/tasks/tasks.py", line 25, in update_instagram_data
    __update_account_direct(account)
  File "/home/antonid08/PycharmProjects/instagramcrm/InstagramWorker/tasks/tasks.py", line 89, in __update_account_direct
    direct_worker.accept_all_pending_requests()
  File "/home/antonid08/PycharmProjects/instagramcrm/InstagramWorker/logic/Direct.py", line 38, in accept_all_pending_requests
    self.__accept_pending_requests(requests_ids)
  File "/home/antonid08/PycharmProjects/instagramcrm/InstagramWorker/logic/Direct.py", line 74, in __accept_pending_requests
    self.__accept_pending_request(request_id)
  File "/home/antonid08/PycharmProjects/instagramcrm/InstagramWorker/logic/Direct.py", line 70, in __accept_pending_request
    return self.api_client.directThreadAction(thread_id, 'approve')
  File "/home/antonid08/.virtualenvs/InstagramVirtualEnv/local/lib/python2.7/site-packages/InstagramAPI/src/Instagram.py", line 461, in directThreadAction
    self.generateSignature(data)  # todo Unresolved reference
AttributeError: Instagram instance has no attribute 'generateSignature`

Not all times.

Guys, where i can find a stable version? I updated package from master and now i have many new critical bugs.

**Comment by ghost** [comment]
Hi, im looking for the same as you, Im looking for an API wich allows accepting follow requests
